version: 1.0.{build}
skip_tags: true
configuration: Debug
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: 58cJ1OMe65ftz1YIfs3TeZEGnL6LFWqbL
before_build:
  - nuget restore "./cs/DungeonCrawler.sln"
build:
  project: /cs/DungeonCrawler.sln
  verbosity: minimal
after_test:
  - cmd: .\after_test.cmd
